name: "Experiment with building in a Linux container"
on:
    push:
      branches:
        - 'container'
jobs:
    build-ubuntu:
        runs-on: ubuntu-latest
        container:
          image: ubuntu:20.04
        env:
            OPENTELEMETRY_MATLAB_INSTALL: "$GITHUB_WORKSPACE/otel_matlab_install"
            DEBIAN_FRONTEND: "noninteractive"
        steps:
            - name: Download OpenTelemetry-Matlab source
              uses: actions/checkout@v3
              with: 
                path: opentelemetry-matlab
            - name: Install compiler and other tools
              run: apt update && apt install -y build-essential git curl pkg-config zip python3 ninja-build
            - name: Install CMake 4.1.2
              run: |
                curl -LO https://github.com/Kitware/CMake/releases/download/v4.1.2/cmake-4.1.2-linux-x86_64.tar.gz
                echo "$GITHUB_WORKSPACE/cmake-4.1.2-linux-x86_64/bin" >> "$GITHUB_PATH"
                ls
                cmake-4.1.2-linux-x86_64/bin/cmake --version
            - name: Install MATLAB
              uses: matlab-actions/setup-matlab@v2
              with:
                release: R2025a
                products: MATLAB_Compiler
            - name: Build OpenTelemetry-Matlab
              working-directory: opentelemetry-matlab
              run: |
                  cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DWITH_OTLP_GRPC=ON -DWITH_OTLP_FILE=ON -DOTEL_MATLAB_VERSION=1.0.0 -DCMAKE_INSTALL_PREFIX=${{ env.OPENTELEMETRY_MATLAB_INSTALL }}
                  cmake --build build --config Release --target install
            - name: Compress into single artifact
              run: tar -czf otel-matlab-ubuntu.tar.gz otel_matlab_install
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with: 
                name: otel-matlab-ubuntu.tar.gz
                path: ./otel-matlab-ubuntu.tar.gz
