name: "Experiment with building in a Linux container"
on:
    push:
      branches:
        - 'container'
jobs:
    build-ubuntu:
        runs-on: ubuntu-22.04
        container:
          image: ubuntu:20.04
        env:
            OPENTELEMETRY_MATLAB_INSTALL: "$GITHUB_WORKSPACE/otel_matlab_install"
            DEBIAN_FRONTEND: "noninteractive"
        steps:
            - name: Download OpenTelemetry-Matlab source
              uses: actions/checkout@v3
              with: 
                path: opentelemetry-matlab
            - name: Install compiler, and Git
              run: apt update && apt install -y build-essential git curl pkg-config zip python3
            - name: Install cmake and ninja
              uses: lukka/get-cmake@latest
              with:
                cmakeVersion: latest
                ninjaVersion: latest
            - name: Install MATLAB
              uses: matlab-actions/setup-matlab@v2
              with:
                release: R2025a
                products: MATLAB_Compiler
            - name: Build OpenTelemetry-Matlab
              working-directory: opentelemetry-matlab
              run: |
                  cmake --trace -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DWITH_OTLP_GRPC=ON -DWITH_OTLP_FILE=ON -DOTEL_MATLAB_VERSION=1.0.0 -DCMAKE_INSTALL_PREFIX=${{ env.OPENTELEMETRY_MATLAB_INSTALL }}
                  cmake --build build --config Release --target install
            - name: Upload log
              uses: actions/upload-artifact@v4
              if: always()
              with:
                name: vcpkg-manifest-install.log
                path: /__w/OpenTelemetry-MATLAB/OpenTelemetry-MATLAB/opentelemetry-matlab/build
            - name: Compress into single artifact
              working-directory: $GITHUB_WORKSPACE
              run: tar -czf otel-matlab-ubuntu.tar.gz otel_matlab_install
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with: 
                name: otel-matlab-ubuntu.tar.gz
                path: $GITHUB_WORKSPACE/otel-matlab-ubuntu.tar.gz
