name: "Debug MacOS Dependencies"
on:
    workflow_dispatch:
    push:
      branches:
        - 'mac_dependencies_2'
jobs:
    build-macos:
        runs-on: macos-14
        env:
            OPENTELEMETRY_MATLAB_INSTALL: "${{ github.workspace }}/otel_matlab_install"
        steps:
            - name: Download OpenTelemetry-Matlab source
              uses: actions/checkout@v3
              with: 
                path: opentelemetry-matlab
            - name: Install ninja-build
              run: brew install ninja
            - name: Install MATLAB
              uses: matlab-actions/setup-matlab@v2
              with:
                release: R2025a
                products: MATLAB_Compiler
            - name: Build OpenTelemetry-Matlab
              working-directory: opentelemetry-matlab
              run: |
                  cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DWITH_OTLP_GRPC=ON -DWITH_OTLP_FILE=ON -DCMAKE_INSTALL_PREFIX=${{ env.OPENTELEMETRY_MATLAB_INSTALL }}
                  cmake --build build --config Release --target install -v
            - name: Compress into single artifact
              working-directory: ${{ github.workspace }}
              run: tar -czf otel-matlab-macos.tar.gz otel_matlab_install
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with: 
                name: otel-matlab-macos.tar.gz
                path: ${{ github.workspace }}/otel-matlab-macos.tar.gz
