name: "Create Multiple .mltbx Files"
on:
    push:
      branches:
        - 'multiple_mltbx'
jobs:
    http-grpc-ubuntu:
        runs-on: ubuntu-22.04
        env:
            OPENTELEMETRY_MATLAB_INSTALL: "${{ github.workspace }}/otel_matlab_install"
        steps:
            - name: Download OpenTelemetry-Matlab source
              uses: actions/checkout@v3
              with: 
                path: opentelemetry-matlab
            - name: Install ninja-build
              run: sudo apt-get install ninja-build
            - name: Install MATLAB
              uses: matlab-actions/setup-matlab@v2
              with:
                release: R2025a
                products: MATLAB_Compiler
            - name: Build OpenTelemetry-Matlab
              working-directory: opentelemetry-matlab
              run: |
                  cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DWITH_OTLP_GRPC=ON -DWITH_OTLP_FILE=ON -DCMAKE_INSTALL_PREFIX=${{ env.OPENTELEMETRY_MATLAB_INSTALL }}
                  cmake --build build --config Release --target install
            - name: Compress into single artifact
              working-directory: ${{ github.workspace }}
              run: tar -czf otel-matlab-httpgrpc-ubuntu.tar.gz otel_matlab_install
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with: 
                name: otel-matlab-httpgrpc-ubuntu.tar.gz
                path: ${{ github.workspace }}/otel-matlab-httpgrpc-ubuntu.tar.gz
    http-ubuntu:
        runs-on: ubuntu-22.04
        env:
            OPENTELEMETRY_MATLAB_INSTALL: "${{ github.workspace }}/otel_matlab_install"
        steps:
            - name: Download OpenTelemetry-Matlab source
              uses: actions/checkout@v3
              with: 
                path: opentelemetry-matlab
            - name: Install ninja-build
              run: sudo apt-get install ninja-build
            - name: Install MATLAB
              uses: matlab-actions/setup-matlab@v2
              with:
                release: R2025a
                products: MATLAB_Compiler
            - name: Build OpenTelemetry-Matlab
              working-directory: opentelemetry-matlab
              run: |
                  cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DWITH_OTLP_FILE=ON -DCMAKE_INSTALL_PREFIX=${{ env.OPENTELEMETRY_MATLAB_INSTALL }}
                  cmake --build build --config Release --target install
            - name: Compress into single artifact
              working-directory: ${{ github.workspace }}
              run: tar -czf otel-matlab-httponly-ubuntu.tar.gz otel_matlab_install
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with: 
                name: otel-matlab-httponly-ubuntu.tar.gz
                path: ${{ github.workspace }}/otel-matlab-httponly-ubuntu.tar.gz
    http-grpc-windows:
        runs-on: windows-latest
        env:
            OPENTELEMETRY_MATLAB_INSTALL: "${{ github.workspace }}/otel_matlab_install"
        steps:
            - name: Download OpenTelemetry-Matlab source
              uses: actions/checkout@v3
              with: 
                path: opentelemetry-matlab
            - name: Install ninja-build
              run: choco install ninja
            - name: Install MATLAB
              uses: matlab-actions/setup-matlab@v2
              with:
                release: R2025a
                products: MATLAB_Compiler
            - name: Build OpenTelemetry-Matlab
              working-directory: opentelemetry-matlab
              shell: cmd
              run: |
                  call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
                  cmake -S . -B build -G Ninja -DCMAKE_CXX_COMPILER="cl.exe" -DCMAKE_C_COMPILER="cl.exe" -DCMAKE_BUILD_TYPE=Release -DWITH_OTLP_GRPC=ON -DWITH_OTLP_FILE=ON -DFETCH_VCPKG=ON -DCMAKE_INSTALL_PREFIX=${{ env.OPENTELEMETRY_MATLAB_INSTALL }}
                  cmake --build build --config Release --target install
            - name: Compress into single artifact
              working-directory: ${{ github.workspace }}
              run: tar -czf otel-matlab-httpgrpc-windows.tar.gz otel_matlab_install
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with: 
                name: otel-matlab-httpgrpc-windows.tar.gz
                path: ${{ github.workspace }}/otel-matlab-httpgrpc-windows.tar.gz
    http-windows:
        runs-on: windows-latest
        env:
            OPENTELEMETRY_MATLAB_INSTALL: "${{ github.workspace }}/otel_matlab_install"
        steps:
            - name: Download OpenTelemetry-Matlab source
              uses: actions/checkout@v3
              with: 
                path: opentelemetry-matlab
            - name: Install ninja-build
              run: choco install ninja
            - name: Install MATLAB
              uses: matlab-actions/setup-matlab@v2
              with:
                release: R2025a
                products: MATLAB_Compiler
            - name: Build OpenTelemetry-Matlab
              working-directory: opentelemetry-matlab
              shell: cmd
              run: |
                  call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
                  cmake -S . -B build -G Ninja -DCMAKE_CXX_COMPILER="cl.exe" -DCMAKE_C_COMPILER="cl.exe" -DCMAKE_BUILD_TYPE=Release -DWITH_OTLP_FILE=ON -DFETCH_VCPKG=ON -DCMAKE_INSTALL_PREFIX=${{ env.OPENTELEMETRY_MATLAB_INSTALL }}
                  cmake --build build --config Release --target install
            - name: Compress into single artifact
              working-directory: ${{ github.workspace }}
              run: tar -czf otel-matlab-httponly-windows.tar.gz otel_matlab_install
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with: 
                name: otel-matlab-httponly-windows.tar.gz
                path: ${{ github.workspace }}/otel-matlab-httponly-windows.tar.gz
    http-grpc-macos:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [macos-13, macos-14]   # runs on Mac with both Intel (macos-13) and Apple Silicon (macos-14) processors
        env:
            OPENTELEMETRY_MATLAB_INSTALL: "${{ github.workspace }}/otel_matlab_install"
        steps:
            - name: Download OpenTelemetry-Matlab source
              uses: actions/checkout@v3
              with: 
                path: opentelemetry-matlab
            - name: Install ninja-build
              run: brew install ninja
            - name: Install MATLAB
              uses: matlab-actions/setup-matlab@v2
              with:
                release: R2025a
                products: MATLAB_Compiler
            - name: Build OpenTelemetry-Matlab
              working-directory: opentelemetry-matlab
              run: |
                  cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DWITH_OTLP_GRPC=ON -DWITH_OTLP_FILE=ON -DCMAKE_INSTALL_PREFIX=${{ env.OPENTELEMETRY_MATLAB_INSTALL }}
                  cmake --build build --config Release --target install
            - name: Compress into single artifact
              working-directory: ${{ github.workspace }}
              run: tar -czf otel-matlab-httpgrpc-${{ matrix.os }}.tar.gz otel_matlab_install
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with: 
                name: otel-matlab-httpgrpc-${{ matrix.os }}.tar.gz
                path: ${{ github.workspace }}/otel-matlab-httpgrpc-${{ matrix.os }}.tar.gz
    http-macos:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [macos-13, macos-14]   # runs on Mac with both Intel (macos-13) and Apple Silicon (macos-14) processors
        env:
            OPENTELEMETRY_MATLAB_INSTALL: "${{ github.workspace }}/otel_matlab_install"
        steps:
            - name: Download OpenTelemetry-Matlab source
              uses: actions/checkout@v3
              with: 
                path: opentelemetry-matlab
            - name: Install ninja-build
              run: brew install ninja
            - name: Install MATLAB
              uses: matlab-actions/setup-matlab@v2
              with:
                release: R2025a
                products: MATLAB_Compiler
            - name: Build OpenTelemetry-Matlab
              working-directory: opentelemetry-matlab
              run: |
                  cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DWITH_OTLP_FILE=ON -DCMAKE_INSTALL_PREFIX=${{ env.OPENTELEMETRY_MATLAB_INSTALL }}
                  cmake --build build --config Release --target install
            - name: Compress into single artifact
              working-directory: ${{ github.workspace }}
              run: tar -czf otel-matlab-httponly-${{ matrix.os }}.tar.gz otel_matlab_install
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with: 
                name: otel-matlab-httponly-${{ matrix.os }}.tar.gz
                path: ${{ github.workspace }}/otel-matlab-httponly-${{ matrix.os }}.tar.gz
    package-mltbx:
        name: Package MATLAB Toolbox (MLTBX) Files
        runs-on: ubuntu-22.04
        permissions:
          contents: write
        needs:
            - http-grpc-ubuntu
            - http-grpc-windows
            - http-grpc-macos
            - http-ubuntu
            - http-windows
            - http-macos
        env:
            OPENTELEMETRY_MATLAB_INSTALL: "${{ github.workspace }}/otel_matlab_install"
        steps:
            - name: Checkout OpenTelemetry-Matlab
              uses: actions/checkout@v3
              with:
                path: OpenTelemetry-Matlab
            - name: Download Artifacts
              uses: actions/download-artifact@v4
              with:
                path: artifacts-downloaded
            - name: Install MATLAB
              uses: matlab-actions/setup-matlab@v2
              with:
                release: R2025a
            - name: Decompress Artifacts with full dependencies
              run: |
                  mkdir http_grpc
                  cd http_grpc
                  mv artifacts-downloaded/*/*httpgrpc*.tar.gz .
                  tar -xzvf otel-matlab-httpgrpc-ubuntu.tar.gz
                  tar -xzvf otel-matlab-httpgrpc-macos-13.tar.gz
                  tar -xzvf otel-matlab-httpgrpc-macos-14.tar.gz
                  tar -xzvf otel-matlab-httpgrpc-windows.tar.gz
            - name: Run commands full dependencies
              env:
                MATLABPATH: OpenTelemetry-Matlab/tools
                WORKING_FOLDER: http_grpc
                OTEL_MATLAB_TOOLBOX_FOLDER: otel_matlab_install
                OTEL_MATLAB_TOOLBOX_OUTPUT_FOLDER: ..
                OTEL_MATLAB_TOOLBOX_VERSION: 
                OTEL_MATLAB_TOOLBOX_NAME: otel-matlab
              uses: matlab-actions/run-command@v1
              with:
                command: packageMatlabInterface
            - name: Decompress Artifacts with minimal dependencies
              run: |
                  mkdir http_only
                  cd http_only
                  mv artifacts-downloaded/*/*httponly*.tar.gz .
                  tar -xzvf otel-matlab-httponly-ubuntu.tar.gz
                  tar -xzvf otel-matlab-httponly-macos-13.tar.gz
                  tar -xzvf otel-matlab-httponly-macos-14.tar.gz
                  tar -xzvf otel-matlab-httponly-windows.tar.gz
            - name: Run commands minimal dependencies
              env:
                MATLABPATH: OpenTelemetry-Matlab/tools
                WORKING_FOLDER: http_only
                OTEL_MATLAB_TOOLBOX_FOLDER: otel_matlab_install
                OTEL_MATLAB_TOOLBOX_OUTPUT_FOLDER: ..
                OTEL_MATLAB_TOOLBOX_VERSION: 
                OTEL_MATLAB_TOOLBOX_NAME: otel-matlab-http-only
              uses: matlab-actions/run-command@v1
              with:
                command: packageMatlabInterface
            - name: Upload artifacts full dependencies
              uses: actions/upload-artifact@v4
              with: 
                name: otel-matlab.mltbx
                path: otel-matlab.mltbx
            - name: Upload artifacts minimal dependencies
              uses: actions/upload-artifact@v4
              with: 
                name: otel-matlab-http-only.mltbx
                path: otel-matlab-http-only.mltbx
